whynotearth/hotel-website-vkirirom.com

src/main.js
Fixes issue #46   
close issue #46
=> Fixes the Route Behavior issue

index.html, src/App.vue, src/components/Contact.vue, src/components/Footer.vue, src/components/Home.vue, src/routes.js
Contact page created.  
Footer links updated.  
Contact Form linked with netlify.  
Font changes on header and other images.  
New background gradient.  
Dynamic Linking of Contact page.
=> New features added, bugs resolved

index.html, src/assets/icons/bed.svg, src/components/Listing.vue
=> book form changes

src/App.vue, src/components/Footer.vue, src/components/Listing.vue, src/components/Toolbar.vue, src/components/searchpage.vue, src/routes.js
Added total price feature, added new footer links, fixed bugs, added a description on the search page for food, added router `:key="$route.name + ($route.params.id || '')"` in router view for dynamic loading of content when changing slugs within same component. Fixed pricing loop.
=> Feature additions and bug fixes

src/components/Listing.vue
solves issue #119 
closes #119
=> single date selection bug

src/components/Listing.vue, src/components/Toolbar.vue
=> pvk page added

.eslintrc.js, .gitignore, package-lock.json, package.json, src/components/Home.vue, src/components/searchpage.vue, src/connection/ajax.js, src/connection/init.js, src/connection/resources.js, src/connection/swagger-axios-config.js, src/constants/connection.js, src/main.js, src/store/modules/auth.js, src/store/modules/reservation.js, src/store/modules/resort.js
Add `swagger-to-axios-codegen` package, remove `vue-resource` package, replace all `this.$http` requests with axios requests.
Every time that swagger API gets an update, we should run `npm run swagger`.
=> add swagger-to-axios-codegen package

package-lock.json, src/components/ReservationFormDesktop.vue, src/components/ReservationFormMobile.vue
=> feat: button fixes

src/connection/swagger-axios-config.js, src/constants/connection.js, src/store/modules/auth.js
=> Fixed: fixed oauth, removed redundant console.logs

src/router/index.ts, src/views/KitchenSink.vue
Add `/testing` page for development purposes (kitchen sink)
=> Add kitchensink

src/App.vue, src/components/BookingBar.vue, src/components/Footer.vue, src/components/Listing.vue, src/components/Toolbar.vue, src/styles/global.scss, src/styles/variables.scss
- add sticky booking bar
- update global .container
- update footer layout
#212
=> Booking flow 1

src/components/BookingBar.vue, src/components/BookingConfirmAndPay.vue, src/components/BookingConfirmBooking.vue, src/components/BookingConfirmDates.vue, src/components/BookingConfirmGuests.vue, src/components/BookingDialog.vue, src/components/BookingReviewPolicies.vue, src/components/Reservation/ConfirmAndPay.vue, src/helpers.ts, src/router/index.ts, src/store/modules/booking.ts, src/styles/global.scss, src/styles/utility.scss, src/views/BookingConfirmAndPay.vue, src/views/BookingReviewPolicies.vue
=> Booking flow 5 [confirm booking]

src/components/BookingConfirmGuests.vue, src/store/modules/booking.ts, src/types.ts
- add bed type section
- add validation and checking capacity
- fix clear booking state when closing modal
I changed the color of the active bed type option. if it's not good, tell me to revert it.
#219
=> fix booking flow 4 [guests]

src/components/AuthDialog.vue, src/components/AuthForgotPassword.vue, src/components/AuthLogin.vue, src/components/AuthLoginExistingAccount.vue, src/components/AuthSignup.vue, src/components/BookingConfirmBooking.vue, src/components/BookingConfirmDates.vue, src/components/BookingConfirmGuests.vue, src/components/BookingCustomerInfo.vue, src/components/BookingDialog.vue, src/store/modules/booking.ts, src/styles/datepicker-dark-theme.scss, src/views/BookingCustomerInfoPage.vue, src/views/BookingPaymentPage.vue, src/views/BookingReviewRulesPage.vue, src/views/BookingThanksPage.vue
- Fix styling issues in booking steps
- Change logic of capacity in guests step
- remove cancel in the last steps of booking.
- add transportation price to booking confirm
=> Fix booking ui issues

src/components/BookingConfirmBooking.vue, src/components/BookingConfirmDates.vue, src/components/BookingPayment.vue, src/components/BookingPaymentByStripe.vue, src/connection/resources.js, src/helpers.ts, src/store/modules/auth.ts, src/store/modules/booking.ts
=> Connect payment to stripe

src/components/BookingConfirmBooking.vue, src/components/BookingCustomerInfo.vue, src/components/BookingNavigation.vue, src/components/BookingPaymentByStripe.vue, src/components/BookingThanks.vue, src/store/modules/booking.ts, src/store/modules/payment.ts, src/views/BookingCustomerInfoPage.vue, src/views/BookingPaymentPage.vue, src/views/BookingThanksPage.vue
- Remove transportation from the price list and contact info page
- Add an external link to the transportation signup system
Link of thanks page is: `/booking/thanks`  
#274
=> transportation - remove transportation, add external link to shuttle signup system

public/index.html
Prevent loading google tag manager in index.html
=> Add condition to load tag manager only in production

src/components/Contact.vue, src/constants/themes.ts, src/styles/variables.scss, src/views/HomePage.vue
=> change primary color to pink

src/components/BookingConfirmBooking.vue, src/components/BookingConfirmDates.vue, src/components/BookingReviewRules.vue, src/store/modules/booking.ts
=> Booking - fix dollar rounding

src/components/PageHomeParrallaxHero.vue, src/styles/variables.scss
- iPhone responsive
- update images
- update logo, make it responsive
- stick layer 6 to bottom
#289
=> Fix parallax images and minor style + responsive

src/router/index.ts, src/views/ContactPage.vue, src/views/SearchPage.vue
fix page top margins, change container, move to views folder
=> move search and contact pages to views, fix basic styles

src/App.vue, src/components/MarkdownBlock.vue, src/components/PageFooter.vue, src/components/ResortDescription.vue, src/components/ResortRules.vue, src/helpers.ts, src/main.ts, src/store/index.ts, src/store/modules/language.ts, src/styles/global-language.scss, src/styles/global-main.scss, src/styles/variables.scss
=> Add language toggle

src/components/BookingPayment.vue, src/components/BookingPaymentByStripe.vue, src/store/modules/booking.ts, src/styles/utility.scss
=> Payment - add address fields, style stripe form

public/index.html, src/components/BookingConfirmBooking.vue, src/styles/variables.scss
**confirm booking:**  
Change fonts and text colors based on design updates
_This should be merged after #309 because width of the card's column is changed there._
=> fix booking confirm typography

.vscode/settings.json, public/index.html, src/components/BookingCustomerInfo.vue, src/components/BookingNavigation.vue, src/components/BookingPayment.vue, src/components/BookingReviewRules.vue, src/components/BookingThanks.vue, src/components/PageHeader.vue, src/store/modules/booking.ts, src/styles/vuetify-material-dark.scss, src/types.ts, src/views/BookingCustomerInfoPage.vue, src/views/BookingPaymentPage.vue, src/views/BookingReviewRulesPage.vue, src/views/BookingThanksPage.vue
#283  
_This PR contains the PR #320_
=> 283 add mobile booking nav

src/components/PageHeader.vue, src/styles/utility.scss, src/styles/variables.scss, src/styles/vuetify-material-dark.scss, src/styles/vuetify-material-light.scss, src/views/HomePage.vue
=> 282 change mobile menu 

src/components/BookingBar.vue, src/components/PageHeader.vue, src/styles/global-main.scss, src/styles/variables.scss, src/views/HomePage.vue, src/views/ListingPage.vue
- fix height of header 
- fix font-weight of booking bar texts
- switch two links location in desktop view of header (make links balanced)
- change h1 color in listing to light color (from `#ffffff`)
#299
=> minor style fixes (header & booking bar & listing)

src/App.vue, src/components/BookingBar.vue, src/components/BookingPayment.vue, src/components/BookingPaymentByStripe.vue, src/constants/app.ts, src/helpers.ts, src/store/modules/booking.ts, src/views/BookingThanksPage.vue, src/views/ListingPage.vue
=> 326 add email notify and enable cash payment

src/components/PageHeader.vue, src/components/PageHomeParrallaxHero.vue, src/styles/variables.scss, src/views/HomePage.vue, src/views/SearchPage.vue
- update page header links (fix /search/menu)
- cleanup search page and remove hardcoded descriptions
- optimize images of parallax and another picture in homepage
- fix footer z-index (bug in mobile in homepage)
- optimize image of hero image in search page
=> minor UI fixes (homepage and searchpage)

src/views/SearchPage.vue
search page - fix undefined issue in hero image #311
=> hotfix search hero image

src/App.vue, src/components/BookingPayment.vue, src/connection/ajax.ts, src/constants/app.ts, src/router/index.ts, src/store/modules/booking.ts
- add email notify on a failed reservation
- handle errors on reservation and sending notify emails (send email just to admins)
- minor fix: clear auth' loading state on app load
#344
=> 344 add better error handling in booking

src/connection/ajax.ts, src/store/modules/booking.ts
fix CORS bug in sending email request
=> booking notify - fix email request

src/helpers.ts, src/store/modules/booking.ts, src/views/ListingPage.vue
=> meta description - remove html tags, show only english

public/index.html, src/components/BookingPayment.vue
=> 349 hide credit card option temporarily

src/connection/ajax.ts, src/connection/resources.js
=> accept-language bug - temporary fix by setting culture=en-US

README.md, netlify.toml, package.json, public/assetlinks.json
Move readme, assetlinks.json and netlify.toml to new version  
Update package.json name and version
=> move master files to new version

public/index.html, src/components/ListingContactForm.vue, src/helpers.ts, src/views/ListingPage.vue
=> 238 Add contact form to listing

public/index.html, src/components/ListingContactForm.vue, src/helpers.ts, src/views/ListingPage.vue
- add contact forms in listing page
=> Develop to master

src/components/ListingContactForm.vue, src/views/ListingPage.vue
=> 238 remove contact form from accommodations pages

package.json, src/components/SnackbarsGlobal.vue, src/registerServiceWorker.ts, src/store/modules/snackbar.ts, vue.config.js
Show a snackbar with Refresh button when there is a new version of site
=> Add notification for new version

.env.example, src/constants/app.ts, src/store/modules/booking.ts, src/types.ts, src/views/BookingThanksPage.vue
- fix total nights number in reservation email
- move hardcoded emails to .env `VUE_APP_EMAIL_BCC_LIST=email1,email2,...`
- skip clearing booking info in test mode `VUE_APP_DEV_MODE=1` for easier testing
=> booking emails - fix total nights undefined and more

src/components/PageHomeParrallaxHero.vue, src/views/HomePage.vue
- remove fade animation of header
- update parallax top margins despite fixing header in homepage
#370
=> home parallax - remove fade animation of header

package.json, public/index.html, src/App.vue, src/components/PageHeader.vue, src/components/PageProgressBarGlobal.vue, src/constants/app.ts, src/helpers.ts, src/main.ts, src/router/index.ts, src/views/ContactPage.vue, src/views/ListingPage.vue, src/views/SearchPage.vue, yarn.lock
- load data before entering listing and search pages and show a loading bar on top of page
- use vue-meta package to set title and description tags
=> Fix title and meta description tags

src/components/MarkdownBlock.vue, src/components/ResortRules.vue, src/helpers.ts, src/plugins/marked.ts, src/styles/markdown-content.scss
=> 383 fix markdown contents

src/components/BookingPayment.vue
Because I want to release a new version, and stripe payment needs @paulchrisluke 's confirmation, I disable it for now.
#271
=> payment - disable card payment temporarily

src/components/BookingPayment.vue
Reverts whynotearth/hotel-website-vkirirom.com#397
payments is ready for testing
=> Revert "payment - disable card payment temporarily"

src/App.vue, src/components/BookingBar.vue, src/components/BookingConfirmBooking.vue, src/components/BookingConfirmDates.vue, src/components/BookingDialog.vue, src/components/BookingReviewRules.vue, src/store/modules/category.ts, src/store/modules/resort.ts, src/views/ListingPage.vue, src/views/SearchPage.vue
- fix navigating same route pages (reported by Sothea)
- refactor structure of resort to prevent not updating views
- remove router-view key
- use beforeRouteUpdate/Enter to observe route changes
#406
=> 406 fix navigating same route pages

src/App.vue, src/components/AuthCore.vue, src/components/AuthLogin.vue, src/components/AuthSignup.vue, src/connection/resources.js, src/store/modules/auth.ts, vue.config.js
- Remove `?culture=en-US` from all resources
- Refactor login and ping, fix ping not showing any message
- Improve error handling of auth
#385
=> 385 fix login returnurl

public/index.html, src/views/HomePage.vue, src/views/ListingPage.vue, src/views/SearchPage.vue
=> #365 JsonLD - add json-ld of home, listing and search pages

src/components/AuthLogin.vue, src/components/AuthLoginExistingAccount.vue, src/components/AuthSignupByEmail.vue, src/components/BookingConfirmDates.vue, src/components/BookingPayment.vue, src/components/PageHeader.vue, src/constants/themes.ts, src/registerServiceWorker.ts
=> change-colors-to-pink

package.json, src/helpers.ts, src/views/HomePage.vue
fix browser title case (home title: no change, search and listing: title case)
=> Fix title case meta title

package.json, src/components/CardProduct.vue, src/mixins.global.ts, src/views/ListingPage.vue
=> 365 add image transformations for listing and search pages

src/components/BookingPayment.vue, src/components/BookingPaymentByStripe.vue, src/store/modules/payment.ts
I forgot to create a PR for this branch, it's just some improvements in payment error handling.
=> stripe - add error handling for initializing stages of payment

public/index.html, src/helpers.ts
This is 1200x630 image for open graph usage:  
https://res.cloudinary.com/die9ji2vn/image/upload/v1581577859/website-static/open-graph-image.jpg
- add open graph tags
- update static JSON-LD in index.html (it will be replaced by API's JSON-LD at runtime)
- change meta description formatter, just limit it to 180 characters.
=> meta - update meta tags

src/App.vue, src/components/AuthLogin.vue, src/connection/ajax.ts, src/helpers.ts, src/store/modules/auth.ts
- Add JWT authentication in addition to cookie
- Fix showing snackbar on login error (show inline error instead)
#385
=> Add jwt, improve error handling of auth

src/views/HomePage.vue
=> 421 home - add description

src/components/BookingPayment.vue
Hotfix validation on fullname field of payment
=> payment - hotfix fullname field validation

netlify.toml
set api to api.whynot.earth for master
=> api - change api url for master branch

public/index.html, src/router/index.ts, vue.config.js
- limit chunks (related to search console errors)  
- change a preconnect value
- disable transpileDependencies for some deps
=> Fix vue config

src/components/PageHomeParrallaxHero.vue, src/styles/variables.scss
=> 451 parallax hero - fix responsive for all sizes, add macbook retina breakpoint

src/App.vue, src/components/PageSplashScreen.vue
=> splash screen - add transition to background and logo

src/connection/ajax.ts
=> hotfix auth

src/views/ListingPage.vue
use mattress instead of beds in camping pages
=> 382 fix camping description

src/components/AuthDialog.vue, src/components/AuthLogin.vue, src/components/BookingBar.vue, src/components/BookingConfirmBooking.vue, src/components/BookingConfirmDates.vue, src/components/BookingConfirmGuests.vue, src/components/BookingCustomerInfo.vue, src/components/BookingDialog.vue, src/components/BookingReviewRules.vue, src/components/BookingThanks.vue, src/store/modules/booking.ts, src/types.ts, src/views/BookingCustomerInfoPage.vue, src/views/BookingReviewRulesPage.vue, src/views/ListingPage.vue
#462 
what to review? check dialogs working without any bug in opening/closing, little changes in choose dates step
=> 462 refactor booking

src/components/AuthDialog.vue, src/components/AuthLogin.vue, src/components/AuthSignupByEmail.vue, src/main.ts, src/store/modules/auth.ts, src/store/store-moderator.ts
=> 396 fix clear user data on logout

src/components/BookingPayment.vue
=> payment - add price on submit button

src/components/BookingBar.vue, src/components/BookingConfirmBooking.vue, src/components/BookingDialog.vue, src/helpers.ts, src/router/index.ts, src/store/modules/booking.ts, src/types.ts
- add step name to URL hash #465
- fix dialog closing animation
- fix dialog content not scrolling to top on step guests and confirm booking
=> booking - fix dialog bugs, add step names to url params

package.json, src/connection/resources.js, src/connection/swagger-axios-config.ts, src/store/modules/auth.ts, src/store/modules/booking.ts, src/store/modules/category.ts, src/store/modules/payment.ts, src/store/modules/resort.ts, yarn.lock
Because of updating OpenApi to v3 (swagger), we need to update swagger-axios-codegen (+ change it's methodNameMode).
=> update swagger-axios-codegen and rename api method names

src/connection/resources.js
was missing in a couple places
=> add hotel in resourcesjs
